import { Metadata } from "next";
import Header from "./component/Header";
import './style.css'

export const metadata:Metadata = {
  title:{
    absolute:"",
    default:'First Next js',
    template:"%s |"
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
